{* DO NOT EDIT THIS FILE! Use an override template instead. *}

This email is to notify you that there is a new item to manage in Usophia Editorial workflow.

To access the item please click below<br>

<a href={$node.url_alias|ezurl}>{$node.name}</a>
